### PR TITLE
Implemented callback: clusterizeInit

### PR DESCRIPTION
**Pull request by Mottie**
This would be a really handy callback to include :grin:

### CODE REVIEW

**Comment by NeXTs** [comment]
Hi Rob!

Thanks for your contribution but I'm wondering regarding benefits of this callback.
I mean we could reach same effect by executing some code right after clusterize initialisation.

```
var clusterize = new Clusterize({
  rows: data,
  scrollId: 'scrollArea',
  contentId: 'contentArea'
});

// do whatever at this point to achieve exact same effect
```

**Comment by Mottie** [comment]
Well, the initialization is delayed when the table comes with thousands of rows already in place - removing, processing, etc. I really needed it to add additional class names to the rows inside the tbody after initialization; but maybe I can work around that.

**Comment by NeXTs** [comment]
Initialization process is fully synchronous despite that rows are already in place or were generated.
So there are no difference between calling function at the end of constructor or next line after `new Clusterize({...})`

**Comment by Mottie** [comment]
Confirmed. Thanks!

**Pull request closed without merging**
